altitude_estimators:

  # The number of model states
  n_model_states: 3

  # The available altitude estimators
  altitude_estimators: [
    "HEIGHT"
  ] 

  # The measured states of the model
  model_states: [
    "HEIGHT", 
    "VELOCITY", 
    "ACCELERATION"
  ] 

  # The available measurements
  measurements: [
    "height_range",
    "vel_baro",
    "acc_imu"
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    HEIGHT: ["height_range", "vel_baro", "acc_imu"]

  # Mapping of measurements to states
  measurement_states:
    height_range: HEIGHT
    vel_baro: VELOCITY
    acc_imu: ACCELERATION

  # Mapping states to model
  state_mapping:
    HEIGHT: [1.0, 0.0, 0.0]
    VELOCITY: [0.0, 1.0, 0.0]
    ACCELERATION: [0.0, 0.0, 1.0]

  n_A:
    HEIGHT: 3

  A:
    HEIGHT: [1, 0.01, 0.0001,
             0, 1, 0.01,
             0, 0, 0.9]

