altitude_estimators:

  # The number of model states
  n_model_states: 3

  # The available altitude estimators
  altitude_estimators: [
    "HEIGHT",
    "PLANE",
    "BRICK",
    "VIO"
  ] 

  # The measured states of the model
  model_states: [
    "HEIGHT", 
    "VELOCITY", 
    "ACCELERATION"
  ] 

  # The available measurements
  measurements: [
    "height_range",
    "height_sonar",
    "height_plane",
    "height_brick",
    "height_vio",
    "vel_baro",
    "acc_imu"
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    HEIGHT: ["height_range", "vel_baro"]
    PLANE: ["height_plane", "vel_baro"]
    BRICK: ["height_brick", "vel_baro"]
    VIO: ["height_vio", "vel_baro"]
    ALOAM: ["height_aloam", "vel_baro"]

  # Mapping of measurements to states
  measurement_states:
    height_range: HEIGHT
    height_sonar: HEIGHT
    height_plane: HEIGHT
    height_brick: HEIGHT
    height_vio: HEIGHT
    vel_baro: VELOCITY
    acc_imu: ACCELERATION

  # Mapping states to model
  state_mapping:
    HEIGHT: [1.0, 0.0, 0.0]
    VELOCITY: [0.0, 1.0, 0.0]
    ACCELERATION: [0.0, 0.0, 1.0]

  n_A:
    HEIGHT: 3
    PLANE: 3
    BRICK: 3
    VIO: 3

  A:
    HEIGHT: [1, 0.01, 0.000,
             0, 1, 0.00,
             0, 0, 0.0]
    PLANE: [1, 0.01, 0.0000,
             0, 1, 0.00,
             0, 0, 0]
    BRICK: [1, 0.01, 0.0000,
             0, 1, 0.00,
             0, 0, 0]
    VIO: [1, 0.01, 0.0000,
             0, 1, 0.00,
             0, 0, 0]
    ALOAM: [1, 0.01, 0.0000,
             0, 1, 0.00,
             0, 0, 0]
height:
  Q: [0.1]
  R: [0.1]
