heading_estimators:

  # The number of model states
  n_model_states: 3

  # The available altitude estimators
  heading_estimators: [
    "PIXHAWK",
    "GYRO",
    "COMPASS",
    "OPTFLOW", 
    "HECTOR",
    "LIDAR",
    "BRICK",
    "VIO",
    "VSLAM",
    "ICP",
  ] 

  # The measured states of the model
  model_states: [
    "YAW", 
    "YAW_RATE", 
    "GYRO_BIAS" 
  ] 

  # The available measurements
  measurements: [
    "yaw_compass",
    "rate_gyro",
    "rate_optflow",
    "yaw_hector",
    "yaw_brick",
    "yaw_vio",
    "yaw_vslam",
    "yaw_lidar",
    "rate_icp",
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    PIXHAWK: []
    GYRO: ["rate_gyro"]
    COMPASS: ["rate_gyro", "yaw_compass"]
    OPTFLOW: ["rate_gyro", "rate_optflow"]
    HECTOR: ["rate_gyro", "yaw_hector"]
    LIDAR: ["rate_gyro", "yaw_lidar"]
    BRICK: ["rate_gyro", "yaw_brick"]
    VIO: ["rate_gyro", "yaw_vio"]
    VSLAM: ["rate_gyro", "yaw_vslam"]
    ICP: ["rate_icp"]
    # BRICK: ["yaw_brick"]

  # Mapping of measurements to states
  measurement_states:
    yaw_compass: YAW
    rate_gyro: YAW_RATE
    rate_optflow: YAW_RATE
    yaw_hector: YAW
    yaw_brick: YAW
    yaw_vio: YAW
    yaw_vslam: YAW
    yaw_lidar: YAW
    rate_icp: YAW_RATE

  # Mapping states to model
  state_mapping:
    YAW: [1.0, 0.0, 0.0]
    YAW_RATE: [0.0, 1.0, 0.0]
    GYRO_BIAS: [0.0, 0.0, 1.0]

