rate: 100 # [Hz]
slow_odom_rate: 2 # [Hz]

averagingNumSamples: 20

# for fusing object altitude
# staticObjectHeight: 0.2 # [m]
# dynamicObjectHeight: 0.2 # [m]

useDifferentialGps: true
max_rtk_correction: 0.25 # [m]
max_altitude_correction: 0.25 # [m]

trg_z_offset: 0.035 # [m]
garmin_z_offset: 0.02 # [m]
mobius_z_offset_: 0.06 # [m]

trgFilterBufferSize: 100
trgFilterMaxValidAltitude: 8.0
trgFilterMaxDifference: 3.0

# objectAltitudeBufferSize: 100
# objectAltitudeValidAltitude: 5.0
# objectAltitudeMaxDifference: 1.0

garminFilterBufferSize: 100
garminFilterMaxValidAltitude: 25.0
garminFilterMaxDifference: 3.0

orientationOffset:

  enabled: false

  x: 0.0
  y: 0.0
  z: 0.0
  w: 0.0

altitude:

  numberOfVariables: 1
  numberOfInputs: 1
  numberOfMeasurements: 1

  A: [1]
  B: [0.01] # 1/rate
  R: [0.001]
  Q: [5000]
  P: [1]

  # bounds for the measurement covariance
  TrgMaxQ: 100000
  TrgMinQ: 0.5

  GarminMaxQ: 100000
  GarminMinQ: 0.5

  # rate for changing the measurement covariance
  TrgQChangeRate: 1000
  GarminQChangeRate: 1000

  # rate for changing the measurement covariance
  TrgQChangeRate: 1000  
  GarminQChangeRate: 1000  
  
  rtkQ: 0.1
  # objectQ: 0.1

  # failsafe for rtk fusion
  rtk_max_down_difference: 1.0
  rtk_max_abs_difference: 5.0

  # failsafe for object altitude fusion
  # object_altitude_max_down_difference: 0.5
  # object_altitude_max_abs_difference: 1.0

lateral:

  numberOfVariables: 2
  numberOfInputs: 2
  numberOfMeasurements: 2

  A: [1, 0,
      0, 1]

  B: [0.01, 0,
      0, 0.01]

  # process covariance
  R: [1.0, 0,
      0, 1.0]

  # measurement covariance
  Q: [10000.0, 0,
      0, 10000.0]

  # measurement mapping
  P: [1, 0,
      0, 1]
