state_estimators:

  # The number of model states
  n_model_states: 6

  # The available state estimators
  state_estimators: [
    "OPTFLOW", 
    "GPS", 
    "OPTFLOWGPS",
    "RTK",
    "ICP",
    "VIO",
    "OBJECT"
  ] 

  # The measured states of the model
  model_states: [
    "POSITION", 
    "VELOCITY", 
    "TILT"
  ] 
  # The available measurements
  measurements: [
    "vel_optflow",
    "pos_mavros",
    "vel_mavros",
    "tilt_mavros",
    "pos_rtk",
    "vel_rtk",
    "pos_icp",
    "vel_icp",
    "pos_vio",
    "vel_vio",
    "pos_object",
    "vel_object"
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    OPTFLOW: ["vel_optflow", "tilt_mavros"]
    GPS: ["pos_mavros", "vel_mavros", "tilt_mavros"]
    OPTFLOWGPS: ["vel_optflow", "pos_mavros", "tilt_mavros"]
    # RTK: ["pos_mavros", "vel_mavros", "tilt_mavros", "pos_rtk"]
    # RTK: ["pos_rtk", "vel_rtk", "tilt_mavros"]
    RTK: ["pos_rtk", "tilt_mavros"]
    ICP: ["tilt_mavros", "pos_icp", "vel_icp"]
    VIO: ["tilt_mavros", "pos_vio"]
    OBJECT: ["tilt_mavros", "pos_object"]

  # Mapping of measurements to states
  measurement_states:
    vel_optflow: VELOCITY
    pos_mavros: POSITION
    vel_mavros: VELOCITY
    tilt_mavros: TILT
    pos_rtk: POSITION
    vel_rtk: VELOCITY
    pos_icp: POSITION
    vel_icp: VELOCITY
    pos_vio: POSITION
    vel_vio: VELOCITY
    pos_object: POSITION
    vel_object: VELOCITY

  # Mapping states to model
  state_mapping:
    POSITION: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    VELOCITY: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
    TILT: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
