state_estimators:

  # The number of model states
  n_model_states: 6

  # The available state estimators
  state_estimators: [
    "OPTFLOW", 
    "GPS", 
    "OPTFLOWGPS",
    "RTK",
    "ICP",
    "VIO"
  ] 

  # The measured states of the model
  model_states: [
    "POSITION", 
    "VELOCITY", 
    "TILT"
  ] 
  # The available measurements
  measurements: [
    "vel_optflow",
    "pos_mavros",
    "vel_mavros",
    "tilt_mavros",
    "pos_rtk",
    "pos_icp",
    "vel_icp",
    "pos_vio",
    "vel_vio"
  ]

  # The fused measurements for each state estimator
  fused_measurements:
    OPTFLOW: ["vel_optflow", "tilt_mavros"]
    GPS: ["pos_mavros", "vel_mavros", "tilt_mavros"]
    OPTFLOWGPS: ["vel_optflow", "pos_mavros", "vel_mavros", "tilt_mavros"]
    RTK: ["pos_mavros", "vel_mavros", "tilt_mavros", "pos_rtk"]
    ICP: ["tilt_mavros", "pos_icp", "vel_icp"]
    VIO: ["tilt_mavros", "pos_vio", "vel_vio"]

  # Mapping of measurements to states
  measurement_states:
    vel_optflow: VELOCITY
    pos_mavros: POSITION
    vel_mavros: VELOCITY
    tilt_mavros: TILT
    pos_rtk: POSITION
    pos_icp: POSITION
    vel_icp: VELOCITY
    pos_vio: POSITION
    vel_vio: VELOCITY

  # Mapping states to model
  state_mapping:
    POSITION: [1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    VELOCITY: [0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
    TILT: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

  # Covariances of measurements
  Q:
    vel_optflow: [100000]
    pos_mavros: [10000]
    vel_mavros: [100000]
    tilt_mavros: [1000000]
    pos_rtk: [1000]
    pos_icp: [1000]
    vel_icp: [10000]
    pos_vio: [1000]
    vel_vio: [10000]

  # The system matrix
  # pos, vel, acc, acc_in, acc_dist, tilt
  A: [1, 0.02, 0, 0, 0, 0,
      0, 1, 0.02, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 0, 6.3512,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 0.9030]

  # The input matrix
  B: [0,
      0,
      0,
      0,
      0,
      0.0970]

  # Process covariance
  R: [1, 0, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 10000000, 0,
      0, 0, 0, 0, 0, 1000]
