rate: 100 # [Hz]
aux_rate: 10 # [Hz]
slow_odom_rate: 2 # [Hz]
diag_rate: 10 # [Hz]
max_altitude_rate: 10 # [Hz]
lkf_states_rate: 10 # [Hz]

# State estimator used for takeoff: OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO
takeoff_estimator: "OPTFLOW"

# available localization methods
gps_available: true
optflow_available: true
vio_available: false
rtk_available: false
lidar_available: false

min_satellites: 6
max_default_altitude: 10.0
max_optflow_altitude: 3.0

averagingNumSamples: 20

# # for fusing object altitude
# staticObjectHeight: 0.2 # [m]
# dynamicObjectHeight: 0.2 # [m]

use_differential_gps: false
publish_fused_odom: true
pass_rtk_as_odom: false # dangerous outside simulation!
max_altitude_correction: 0.25 # [m]

trg_z_offset: 0.035 # [m]
garmin_z_offset: 0.02 # [m]
# mobius_z_offset: 0.06 # [m]

trgFilterBufferSize: 100
trgFilterMaxValidAltitude: 8.0
trgFilterMaxDifference: 3.0

# objectAltitudeBufferSize: 100
# objectAltitudeValidAltitude: 5.0
# objectAltitudeMaxDifference: 1.0

garminFilterBufferSize: 100
garminFilterMaxValidAltitude: 25.0
garminFilterMaxDifference: 3.0

altitude:

  numberOfVariables: 1
  numberOfInputs: 1
  numberOfMeasurements: 1

  A: [1]
  B: [0.01] # 1/rate
  R: [0.001]
  Q: [5000]
  P: [1]

  # bounds for the measurement covariance
  TrgMaxQ: 100000
  TrgMinQ: 0.5

  GarminMaxQ: 100000
  GarminMinQ: 0.5

  # rate for changing the measurement covariance
  TrgQChangeRate: 1000  
  GarminQChangeRate: 1000  

  rtkQ: 0.1
  # objectQ: 0.1

  # failsafe for rtk fusion
  rtk_max_down_difference: 1.0
  rtk_max_abs_difference: 5.0

  # failsafe for object altitude fusion
  # object_altitude_max_down_difference: 0.5
  # object_altitude_max_abs_difference: 1.0

lateral:

  numberOfVariables: 6
  numberOfInputs: 1
  numberOfMeasurements: 1

  max_pos_correction_rate: 20.0 # [?/s]

  A: [1, 0.02, 0, 0, 0, 0,
      0, 1, 0.02, 0, 0, 0,
      0, 0, 0, 1, 1, 0,
      0, 0, 0, 0, 0, 6.3512,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 0.9030]

  B: [0,
      0,
      0,
      0,
      0, 
      0.0970]

  # process covariance
  R: [1, 0, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 10000000, 0,
      0, 0, 0, 0, 0, 1000]

  # measurement covariances
  dynamic_optflow_cov: false
