# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "OPTFLOW"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "OPTFLOW" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["OPTFLOW", "HECTOR"]

heading_estimators:
  active: ["GYRO", "OPTFLOW", "HECTOR"]

# Available localization methods
gps_available: false
optflow_available: true
vio_available: false
rtk_available: false
lidar_available: true
brick_available: false
t265_available: false

lateral:

  # Process covariance
  R: [1, 1, 1, 0, 0, 0,
      0, 1, 1, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 0.1,
      0, 0, 0, 0, 0.01, 0,
      0, 0, 0, 0, 0, 1000]

  Q:
    vel_optflow: [1]
    pos_hector: [1]
    tilt_mavros: [100]
