# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "HECTOR"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "HECTOR" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["HECTOR"]

heading_estimators:
  active: ["GYRO", "HECTOR"]

# Available localization methods
gps_available: false
optflow_available: false
vio_available: false
rtk_available: false
lidar_available: false
aloam_available: true
brick_available: false
t265_available: false

publish_local_origin_stable_tf: false 

lateral:

  Q:
    vel_optflow: [1]
    pos_hector: [10]
    tilt_mavros: [100]
