# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "GPS"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "PIXHAWK" 

# Available localization methods
gps_available: true
optflow_available: false
vio_available: false
rtk_available: true
lidar_available: false
brick_available: false
t265_available: false
