# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, LIDAR, VIO, VSLAM, HECTOR
lateral_estimator: "LIDAR"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "LIDAR" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["LIDAR"]

heading_estimators:
  active: ["GYRO", "LIDAR"]

# Available localization methods
gps_available: false
optflow_available: true
vio_available: false
rtk_available: false
lidar_available: true
brick_available: false
t265_available: false
