rate: 100 # [Hz]
aux_rate: 10 # [Hz]
slow_odom_rate: 2 # [Hz]
diag_rate: 10 # [Hz]
max_altitude_rate: 10 # [Hz]
lkf_states_rate: 10 # [Hz]

# State estimator used for takeoff: OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO
takeoff_estimator: "GPS"

# available localization methods
gps_available: true
optflow_available: false
vio_available: false
rtk_available: false
lidar_available: false
object_available: false

min_satellites: 0
max_default_altitude: 10.0
max_optflow_altitude: 3.0
april_objects: false

use_differential_gps: false
publish_fused_odom: true # otherwise publish pixhawk odometry instead
pass_rtk_as_odom: false # dangerous outside simulation!
max_altitude_correction: 0.25 # [m]

trg_z_offset: 0.035 # [m]
garmin_z_offset: 0.02 # [m]
# mobius_z_offset: 0.06 # [m]
fcu_height: 0.2 # [m]

trgFilterBufferSize: 100
trgFilterMaxValidAltitude: 8.0
trgFilterMaxDifference: 3.0

# objectAltitudeBufferSize: 100
# objectAltitudeValidAltitude: 5.0
# objectAltitudeMaxDifference: 1.0

garminFilterBufferSize: 100
garminFilterMaxValidAltitude: 25.0
garminFilterMaxDifference: 3.0

null_tracker: "mrs_mav_manager/NullTracker"

altitude:

  # ALTITUDE - barometric, HEIGHT - rangefinder
  altitude_estimator: "HEIGHT"
  estimate_elevation: false
  estimate_baro_offset: true

  # z-axis (altitude, height) velocity limit for barometer offset estimation
  # we want to estimate the offset only when both the alititude and height is not changing to prevent false measurements
  max_vel_baro_offset_estimation: 0.2 # [m/s]

  # changes of elevation under this value will be treated as flat terrain
  elevation_tolerance: 0.5 # [m]

  # do not fuse rangefinder measurements when the UAV is tilted more than this angle
  excessive_tilt: 0.5 # ~pi/6 [rad]

  # Altitude Kalman filter parameters
  numberOfVariables: 6
  numberOfInputs: 1
  numberOfMeasurements: 1

  # The system matrix
  # altitude, velocity, acceleration, height, elevation, offset
  # altitude = height + elevation
  A: [1, 0.02, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0,
      0, 0, 1, 0.02, 0, 0, 
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 1]

  # The input matrix
  B: [0,
      0,
      0,
      0,
      0,
      0]

  # Process covariance
  R: [1, 0, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 1]

  # Covariances of measurements
  Q:
    alt_baro: [100]
    height_range: [1000] # 0.04 stddev in simulation
    vel_mavros: [0.001]
    bias_baro: [0.1] 
    elevation: [0.01] 

  # bounds for the measurement covariance
  TrgMaxQ: 100000
  TrgMinQ: 0.5

  GarminMaxQ: 100000
  GarminMinQ: 0.5

  # rate for changing the measurement covariance
  TrgQChangeRate: 1000
  GarminQChangeRate: 1000

  rtkQ: 0.1
  # objectQ: 0.1

  # failsafe for rtk fusion
  rtk_max_down_difference: 1.0
  rtk_max_abs_difference: 5.0

  # failsafe for object altitude fusion
  # object_altitude_max_down_difference: 0.5
  # object_altitude_max_abs_difference: 1.0

lateral:

  numberOfVariables: 6
  numberOfInputs: 1
  numberOfMeasurements: 1

  saturate_mavros_position: false
  max_mavros_pos_correction: 0.5
  max_vio_pos_correction: 0.5
  max_object_pos_correction: 0.5
  max_rtk_pos_correction: 0.1
  rtk_fuse_sps: true

  dynamic_optflow_cov: false

  # Covariances of measurements
  Q:
    vel_optflow: [1000000000]
    pos_mavros: [10000]
    vel_mavros: [100000]
    tilt_mavros: [1000000]
    pos_rtk: [1000]
    vel_rtk: [10000]
    pos_icp: [1000]
    vel_icp: [10000]
    pos_vio: [100000]
    vel_vio: [10000]
    pos_object: [1000]
    vel_object: [10000]

  # The system matrix
  # pos, vel, acc, acc_in, acc_dist, tilt
  A: [1, 0.02, 0, 0, 0, 0,
      0, 1, 0.02, 0, 0, 0,
      0, 0, 0, 1, 1, 0,
      0, 0, 0, 0, 0, 6.3512,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 0.9030]

  # The input matrix
  B: [0,
      0,
      0,
      0,
      0,
      0.0970]

  # Process covariance
  R: [1, 0, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 10000000, 0,
      0, 0, 0, 0, 0, 1000]

  # RTK estimator must have a different model
  rtk:

    A: [1, 0,
        0, 1]

    B: [0.01, 0,
        0, 0.01]

    R: [0.01, 0,
        0, 0.01]

    Q: [100, 0,
        0, 100]

    P: [1, 0,
        0, 1]

heading:

  use_heading_estimator: false # otherwise use PixHawk heading estimate
  gyro_fallback: false
  heading_estimator: "COMPASS" # GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow

  numberOfVariables: 3
  numberOfInputs: 2
  numberOfMeasurements: 1

  optflow_yaw_rate_filter_buffer_size: 100
  optflow_yaw_rate_filter_max_valid: 3.0
  optflow_yaw_rate_filter_max_diff: 3.0

  compass_yaw_filter_buffer_size: 100
  compass_yaw_filter_max_diff: deg(45)

  # Model is unidentified!!!
  # The system matrix (add gyro gain? EKF needed)
  A: [1, 0.02, 0,  # yaw
      0, 0.9, 0,     # yaw rate
      0, 0, 0]     # gyro bias

  # The input matrix (yaw rate or yaw + yaw rate?)
  B: [0, 0,
      0, 0.1,
      0, 0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.000001]

  # Covariances of measurements
  Q:
    yaw_compass: [0.1]
    rate_gyro: [0.1]
    rate_optflow: [0.1]
