lateral:

  optflow_median_filter: true
  optflow_filter_buffer_size: 50
  optflow_filter_max_valid: 5.0
  optflow_filter_max_diff: 1.0

  gps_fallback:
    allowed: false
    fallback_estimator: "OPTFLOW"
    cov_limit: 10.0 # limit covariance in lateral axes to toggle fallback
    bad_samples: 300 # samples with large covariance before fallback (100 samples ~ 1 second)
    altitude: 4.0 # go to altitude before fallback (optflow should work up to 10 m)
    return_after_ok: true # return to GPS when covariance is back to normal
    cov_ok: 6.0 # threshold covariance for return from fallback
    good_samples: 300 # samples with normal covariance before returning from fallback (100 samples ~ 1 second)

  # Covariances of measurements
  R:
    vel_optflow: [0.1]

heading:

  # Covariances of measurements
  R:
    hdg_compass: [0.1]
    hdg_hector: [0.01]
    hdg_brick: [1]
    hdg_vio: [1]
    hdg_vslam: [1]
    hdg_lidar: [1]
    rate_gyro: [0.1]
    rate_optflow: [10]
    rate_icp: [1]
