
altitude:

  # The input matrix
  B: [0,
      0,
      0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 1, 0,
      0, 0, 0.1]

  # Covariances of measurements
  Q:
    height_range: [10] # 0.04 stddev in simulation
    height_sonar: [1000] # 0.04 stddev in simulation
    height_plane: [1] 
    height_brick: [1] 
    height_vio: [1] 
    vel_baro: [1]
    acc_imu: [1]

lateral:

  optflow_median_filter: true
  optflow_filter_buffer_size: 50
  optflow_filter_max_valid: 5.0
  optflow_filter_max_diff: 1.0

  # Covariances of measurements
  Q:
    vel_optflow: [1]

heading:

  # The system matrix 
  A: [1, 0.02, 0,  # yaw
      0, 0.9, 1,     # yaw rate
      0, 0, 1]     # gyro bias

  # The input matrix (yaw rate or yaw + yaw rate?)
  B: [0, 0,
      0, 0.1,
      0, 0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.00001]

  # Covariances of measurements
  Q:
    yaw_compass: [0.1]
    yaw_hector: [0.01]
    yaw_brick: [1]
    yaw_vio: [1]
    yaw_vslam: [1]
    yaw_lidar: [1]
    rate_gyro: [0.1]
    rate_optflow: [10]
    rate_icp: [100]
