# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "GPS"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "PIXHAWK" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["OPTFLOW", "GPS", "RTK", "VIO", "BRICK", "HECTOR"]

heading_estimators:
  active: ["PIXHAWK", "GYRO", "COMPASS", "OPTFLOW", "HECTOR", "BRICK"]

# Available localization methods
gps_available: true
optflow_available: true
vio_available: true
rtk_available: true
lidar_available: true
brick_available: true
t265_available: false

# Rates of odometry publishers
rate: 100 # [Hz]
aux_rate: 1 # [Hz]
slow_odom_rate: 2 # [Hz]
diag_rate: 10 # [Hz]
max_altitude_rate: 1 # [Hz]
lkf_states_rate: 10 # [Hz]

min_satellites: 0
max_default_altitude: 20.0
max_optflow_altitude: 10.0
april_objects: false

publish_fused_odom: true # otherwise publish pixhawk odometry instead
publish_local_origin_stable_tf: true 
publish_pixhawk_velocity: false # pixhawk velocity instead of estimated velocity - sometimes works better
pass_rtk_as_odom: false # dangerous outside simulation!
max_altitude_correction: 0.5 # [m]

trg_z_offset: 0.035 # [m]
garmin_z_offset: -0.03 # [m]
sonar_z_offset: 0.0 # [m]
# mobius_z_offset: 0.06 # [m]
fcu_height: 0.2 # [m]

trgFilterBufferSize: 100
trgFilterMaxValidAltitude: 8.0
trgFilterMaxDifference: 3.0

garminFilterBufferSize: 100
garminFilterMaxValidAltitude: 40.0
garminFilterMaxDifference: 1.0

sonarFilterBufferSize: 200
sonarFilterMaxValidAltitude: 40.0
sonarFilterMaxDifference: 1.0

null_tracker: "NullTracker"

altitude:

  # do not fuse rangefinder measurements when the UAV is tilted more than this angle
  excessive_tilt: 0.5 # ~pi/6 [rad]

  # Altitude Kalman filter parameters
  numberOfVariables: 3
  numberOfInputs: 1
  numberOfMeasurements: 1

  # The input matrix
  B: [0,
      0,
      0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.1]

  # Covariances of measurements
  Q:
    height_range: [10] # 0.04 stddev in simulation
    height_sonar: [10] # 0.04 stddev in simulation
    vel_baro: [0.1]
    acc_imu: [1]

lateral:

  numberOfVariables: 6
  numberOfInputs: 1
  numberOfMeasurements: 1

  saturate_mavros_position: false
  max_mavros_pos_correction: 0.5
  max_vio_pos_correction: 0.5
  max_object_pos_correction: 0.5
  max_brick_pos_correction: 1.0
  max_rtk_pos_correction: 0.2
  max_t265_vel: 10.0
  rtk_fuse_sps: true

  dynamic_optflow_cov: false
  dynamic_optflow_cov_scale: 100000000

  optflow_median_filter: true
  optflow_filter_buffer_size: 50
  optflow_filter_max_valid: 5.0
  optflow_filter_max_diff: 1.0

  icp_vel_median_filter: true
  icp_vel_filter_buffer_size: 50
  icp_vel_filter_max_valid: 8.0
  icp_vel_filter_max_diff: 3.0

  hector_pos_median_filter: true
  hector_pos_filter_buffer_size: 50
  hector_pos_filter_max_valid: 8.0
  hector_pos_filter_max_diff: 3.0

  brick_pos_median_filter: false
  brick_pos_filter_buffer_size: 50
  brick_pos_filter_max_valid: 8.0
  brick_pos_filter_max_diff: 3.0

  # Covariances of measurements
  Q:
    vel_optflow: [1]
    pos_mavros: [0.1]
    vel_mavros: [1]
    tilt_mavros: [100]
    pos_rtk: [10]
    vel_rtk: [1000]
    pos_icp: [1000]
    vel_icp: [10000]
    pos_vio: [100]
    vel_vio: [10000]
    pos_object: [100]
    vel_object: [10000]
    pos_brick: [1000]
    vel_brick: [10000]
    pos_hector: [1]

  # The system matrix
  # pos, vel, acc, acc_in, acc_dist, tilt
  A: [1, 0.02, 0.0004, 0, 0, 0,
      0, 1, 0.02, 0, 0, 0,
      0, 0, 0, 1, 1, 0,
      0, 0, 0, 0, 0, 6.3512,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 0.9030]

  # The input matrix
  B: [0,
      0,
      0,
      0,
      0,
      0.0970]

  # Process covariance
  R: [1, 1, 1, 0, 0, 0,
      0, 1, 1, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 0.0001,
      0, 0, 0, 0, 0.1, 0,
      0, 0, 0, 0, 0, 1000]

  # RTK estimator must have a different model
  rtk:

    A: [1, 0,
        0, 1]

    B: [0.01, 0,
        0, 0.01]

    R: [0.01, 0,
        0, 0.01]

    Q: [10, 0,
        0, 10]

    P: [1, 0,
        0, 1]

heading:

  gyro_fallback: true

  numberOfVariables: 3
  numberOfInputs: 2
  numberOfMeasurements: 1

  optflow_yaw_rate_filter_buffer_size: 100
  optflow_yaw_rate_filter_max_valid: 3.0
  optflow_yaw_rate_filter_max_diff: 3.0

  compass_yaw_filter_buffer_size: 100
  compass_yaw_filter_max_diff: deg(45)

  hector_yaw_median_filter: true
  hector_yaw_filter_buffer_size: 100
  hector_yaw_filter_max_diff: deg(10)

  brick_yaw_median_filter: true
  brick_yaw_filter_buffer_size: 100
  brick_yaw_filter_max_diff: deg(10)
  max_brick_yaw_correction: deg(1)
  accum_yaw_brick_alpha: 0.1

  # Model is unidentified!!!
  # The system matrix (add gyro gain? EKF needed)
  A: [1, 0.02, 0,  # yaw
      0, 0.9, 1,     # yaw rate
      0, 0, 1]     # gyro bias

  # The input matrix (yaw rate or yaw + yaw rate?)
  B: [0, 0,
      0, 0.1,
      0, 0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0.1,
      0, 0, 0.00001]

  # Covariances of measurements
  Q:
    yaw_compass: [0.1]
    yaw_hector: [0.01]
    yaw_brick: [1]
    rate_gyro: [0.1]
    rate_optflow: [10]
