
altitude:

  # The input matrix
  B: [0,
      0,
      0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.1]

  # Covariances of measurements
  Q:
    height_range: [1000] # 0.04 stddev in simulation
    height_sonar: [1000] # 0.04 stddev in simulation
    height_plane: [1] 
    height_brick: [1] 
    height_vio: [1] 
    vel_baro: [0.1]
    acc_imu: [1]

lateral:

  optflow_median_filter: true
  optflow_filter_buffer_size: 50
  optflow_filter_max_valid: 5.0
  optflow_filter_max_diff: 1.0

  # Covariances of measurements
  Q:
    vel_optflow: [1]
    pos_mavros: [0.01]
    vel_mavros: [0.1]
    tilt_mavros: [100]
    pos_rtk: [10]
    vel_rtk: [1000]
    pos_lidar: [1]
    vel_lidar: [10]
    pos_vslam: [1000]
    pos_vio: [100]
    vel_vio: [10000]
    pos_object: [100]
    vel_object: [10000]
    pos_brick: [100]
    vel_brick: [10000]
    pos_hector: [1.0]
    vel_icp: [1000]


  # Faster integration of disturbances should mitigate velocity error caused by integrating body disturbances in world frame !may become unstable!
  R: [1, 1, 1, 0, 0, 0,
      0, 1, 1, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 1,
      0, 0, 0, 0, 1, 0,
      0, 0, 0, 0, 0, 1000]

heading:

  # The system matrix 
  A: [1, 0.02, 0,  # yaw
      0, 0.9, 1,     # yaw rate
      0, 0, 1]     # gyro bias

  # The input matrix (yaw rate or yaw + yaw rate?)
  B: [0, 0,
      0, 0.1,
      0, 0]

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0.1,
      0, 0, 0.00001]

  # Covariances of measurements
  Q:
    yaw_compass: [0.1]
    yaw_hector: [0.01]
    yaw_brick: [1]
    yaw_vio: [1]
    yaw_vslam: [1]
    yaw_lidar: [1]
    rate_gyro: [0.1]
    rate_optflow: [10]
    rate_icp: [100]
