# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "VIO"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "VIO" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["GPS", "VIO"]

heading_estimators:
  active: ["PIXHAWK", "GYRO", "VIO"]

# Available localization methods
gps_available: true
optflow_available: false
vio_available: true
rtk_available: true
lidar_available: false
object_available: false
t265_available: false
