# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "GPS"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "PIXHAWK" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["GPS", "OPTFLOW", "BRICKFLOW", "BRICK"]

heading_estimators:
  active: ["PIXHAWK", "GYRO", "OPTFLOW", "BRICKFLOW", "BRICK"]

lateral:
  # Covariances of measurements
  Q:
    pos_brick: [10]
    vel_optflow: [10]
    tilt_mavros: [100]

  # Process covariance
  R: [1, 10, 0, 0, 0, 0,
      0, 1, 1000, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 0.0001,
      0, 0, 0, 0, 0.1, 0,
      0, 0, 0, 0, 0, 1000]

