# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "ALOAM"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "ALOAM"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "ALOAM" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["ALOAM"]

heading_estimators:
  active: ["GYRO", "ALOAM"]

# Available localization methods
gps_available: false
optflow_available: false
vio_available: false
rtk_available: false
lidar_available: false
aloam_available: true
brick_available: false
t265_available: false

lateral:
  # Covariances of measurements
  Q:
    pos_mavros: [10]
    vel_mavros: [1000]
    pos_aloam: [10]

heading:
  # Covariances of measurements
  Q:
    yaw_aloam: [0.1]
    rate_gyro: [0.1]
altitude:
  Q:
    height_aloam: [1]

garmin_z_offset: -0.01 # [m]
fcu_height: 0.0 # [m]

aloamHeightFilterBufferSize: 200
aloamHeightFilterMaxValidAltitude: 40.0
aloamHeightFilterMaxDifference: 2.0
