# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "HECTOR"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "HECTOR" 

# Lateral estimator parameters
lateral:

  # Covariances of measurements
  Q:
    vel_optflow: [10000]
    tilt_mavros: [100]
    vel_icp: [10000]
    pos_hector: [1000]

  # Process covariance
  R: [1, 1, 1, 0, 0, 0,
      0, 1, 1, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 0.0001,
      0, 0, 0, 0, 0.0001, 0,
      0, 0, 0, 0, 0, 1000]

# Altitude estimator parameters
altitude:

  # Process covariance
  R: [0.1, 0, 0, 0, 0, 0,
      0, 0.1, 0, 0, 0, 0,
      0, 0, 0.1, 0, 0, 0,
      0, 0, 0, 0.1, 0, 0,
      0, 0, 0, 0, 0.1, 0,
      0, 0, 0, 0, 0, 0.1]

  # Covariances of measurements
  Q:
    alt_baro: [0.01]
    height_range: [100] # 0.04 stddev in simulation
    vel_mavros: [0.001]

# Heading estimator parameters
heading:

  gyro_fallback: false

  optflow_yaw_rate_filter_buffer_size: 100
  optflow_yaw_rate_filter_max_valid: 3.0
  optflow_yaw_rate_filter_max_diff: 3.0

  hector_yaw_median_filter: true
  hector_yaw_filter_buffer_size: 100
  hector_yaw_filter_max_diff: deg(10)

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.000001]

  # Covariances of measurements
  Q:
    yaw_compass: [0.1]
    yaw_hector: [100]
    rate_gyro: [0.1]
    rate_optflow: [10]
