# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "GPS"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "PIXHAWK" 

# Lateral estimator parameters
lateral:

  # Covariances of measurements
  Q:
    pos_mavros: [1000]
    vel_mavros: [10000]
    tilt_mavros: [100]
    pos_rtk: [10]

  # Process covariance
  R: [1, 1, 1, 0, 0, 0,
      0, 1, 1, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 0.0001,
      0, 0, 0, 0, 0.0001, 0,
      0, 0, 0, 0, 0, 1000]

# Altitude estimator parameters
altitude:

  # Process covariance
  R: [0.1, 0, 0, 0, 0, 0,
      0, 0.1, 0, 0, 0, 0,
      0, 0, 0.1, 0, 0, 0,
      0, 0, 0, 0.1, 0, 0,
      0, 0, 0, 0, 0.1, 0,
      0, 0, 0, 0, 0, 0.1]

  # Covariances of measurements
  Q:
    alt_baro: [0.01]
    height_range: [100] # 0.04 stddev in simulation
    vel_mavros: [0.001]

# Heading estimator parameters
heading:

  gyro_fallback: false

  compass_yaw_filter_buffer_size: 100
  compass_yaw_filter_max_diff: deg(45)

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.000001]

  # Covariances of measurements
  Q:
    yaw_compass: [0.1]
    rate_gyro: [0.1]
