# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "OPTFLOW"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "OPTFLOW" 

# Lateral estimator parameters
lateral:

  optflow_median_filter: true
  optflow_filter_buffer_size: 50
  optflow_filter_max_valid: 5.0
  optflow_filter_max_diff: 1.0

  # Covariances of measurements
  Q:
    vel_optflow: [10000]
    tilt_mavros: [100]

  # Process covariance
  R: [1, 0, 0, 0, 0, 0,
      0, 1, 0, 0, 0, 0,
      0, 0, 1, 0, 0, 0,
      0, 0, 0, 1, 0, 0,
      0, 0, 0, 0, 10000000, 0,
      0, 0, 0, 0, 0, 1000]

# Altitude estimator parameters
altitude:

  # Process covariance
  R: [0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0,
      0, 0, 0.1, 0, 0, 0,
      0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0,
      0, 0, 0, 0, 0, 0]

  # Covariances of measurements
  Q:
    alt_baro: [0.01]
    height_range: [0.1] # 0.04 stddev in simulation
    vel_mavros: [0.001]
  
# Heading estimator parameters
heading:

  gyro_fallback: false

  optflow_yaw_rate_filter_buffer_size: 100
  optflow_yaw_rate_filter_max_valid: 3.0
  optflow_yaw_rate_filter_max_diff: 3.0

  # Process covariance
  R: [0.1, 0, 0,
      0, 0.1, 0,
      0, 0, 0.000001]

  # Covariances of measurements
  Q:
    rate_gyro: [0.1]
    rate_optflow: [0.1]
