# Estimators used during takeoff
# Lateral state estimator:
# OPTFLOW, GPS, OPTFLOWGPS, RTK, ICP, VIO, HECTOR
lateral_estimator: "OPTFLOW"

# Altitude state estimator:
# HEIGHT - rangefinder
altitude_estimator: "HEIGHT"

# Heading state estimator:
# GYRO - gyro, COMPASS - gyro, compass, OPTFLOW - gyro, optflow, HECTOR - gyro, hector slam
heading_estimator: "OPTFLOW" 

# Active estimators are started at node launch and can be switched to during flight
state_estimators:
  active: ["GPS", "OPTFLOW"]

heading_estimators:
  active: ["PIXHAWK", "GYRO", "OPTFLOW"]

lateral:
  # Covariances of measurements
  Q:
    vel_optflow: [0.1]
    tilt_mavros: [100]

  # Process covariance
  R: [1, 0.1, 0, 0, 0, 0,
      0, 1, 1000, 0, 0, 0,
      0, 0, 0, 0.0001, 0.0001, 0,
      0, 0, 0, 0, 0, 0.0001,
      0, 0, 0, 0, 0.1, 0,
      0, 0, 0, 0, 0, 1000]

